### ISSUE TITLE
[Error - <time stamp>] Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by tolga-balci** [Aeraphe/xvba-repo#17]
## Installation
**Windows 11** 22H2 (OS Build 22621.2283)
**VSCode Version: 1.82.3 (user setup)**
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T10:51:22.294Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
**VSCode installed extensions** all by Microsoft, at the latest version
- Jupyter
- Jupyter Cell Tags
- Jupyter Keymap
- Jupyter Notebook Renderers
- Jupyter Slide Show
- Pylance
- Python
- WSL

**XVBA Version 2023-8-4, 05:20:38** (installed from VS Code Extensions menu)
**Excel Macro Settings** under Trust Center -> Macro settings
[Selected] Enable VBA macros (not recommended; potentially dangerous code can run)
[**De**selected] Enable Excel 4.0 macros when VBA macros are enabled
[Selected] Trust access to the VBA project object model.

## Expected behavior
* XVBA server starts
* Plugin is usable

## Current behavior
Plugin errors and is not usable. Please see short Error log below. Debug error log captured in a text file.

## Steps to reproduce
1. Install VS Code
2. Go to Extensions from the left menu
3. Search for XVBA extension
4. Click "Install" in the XVBA - Live Server VBA page.
5. When installation finishes, a debug log is written to the terminal. Then the following Error log is displayed with the notification banner "The Language Server For VBA server crashed 5 times in the last 3 minutes. The server will not be restarted."

## Error log (short)
```
TypeError: Cannot read properties of null (reading '0')
    at c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:95293
    at Generator.next (<anonymous>)
    at c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:94873
    at new Promise (<anonymous>)
    at r (c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:94618)
    at t.InitializeLanguageServerFeatures (c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:95176)
    at c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:259486
    at Generator.next (<anonymous>)
    at c:\Users\Tolga.Balci\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:259147
    at new Promise (<anonymous>)

Node.js v18.15.0
[Error - 1:35:21 PM] Connection to server got closed. Server will not be restarted.
```

`
The Language Server For VBA server crashed 5 times in the last 3 minutes. The server will not be restarted.
`

----
Edit:
- Add Excel Macro settings
- Add VSCode installed extensions

**Comment by spike1234** [comment]
I have the same issue
@tolga-balci did you manage to solve this?

**Comment by tolga-balci** [comment]
Unfortunately not @spike1234

**Comment by lda87565** [comment]
Same here..

TypeError: Cannot read properties of null (reading '0')
    at c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:95293
    at Generator.next (<anonymous>)
    at c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:94873
    at new Promise (<anonymous>)
    at r (c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:94618)
    at t.InitializeLanguageServerFeatures (c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:95176)
    at c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:259486
    at Generator.next (<anonymous>)
    at c:\Users\larsd\.vscode\extensions\local-smart.excel-live-server-4.0.30\dist\bundle.js:1:259147
    at new Promise (<anonymous>)

Node.js v18.15.0
[Error - 8:09:00 AM] Connection to server got closed. Server will not be restarted.

**Comment by lda87565** [comment]
Found out that the server starts, when downgrading to version v4.0.5.

But, I still cannot create a VBA project from menu. I get this permission error:

Error running command excel-live-server.bootstrap: A system error occurred (EPERM: operation not permitted, mkdir 'logs'). This is likely caused by the extension that contributes excel-live-server.bootstrap.

Anybody knows how to fix this?

**Comment by interSAP** [comment]
Same here. 
Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
